# Generated by Django 4.2.7 on 2025-06-17 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre interno del archivo', max_length=50)),
                ('label', models.CharField(blank=True, help_text='Nombre para mostrar', max_length=50)),
                ('description', models.CharField(blank=True, help_text='Descripción de la versión', max_length=100)),
                ('file', models.CharField(help_text='Nombre del archivo .bbli/.bblx', max_length=50)),
                ('visible', models.BooleanField(default=True, help_text='¿Es visible en la interfaz?')),
                ('activo', models.BooleanField(default=False, help_text='¿Está activa para mostrar en paralelo?')),
            ],
            options={
                'verbose_name': 'Biblia',
                'verbose_name_plural': 'Biblias',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(help_text='Número del libro (1-66)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(66)])),
                ('name', models.CharField(help_text='Nombre del libro', max_length=50)),
                ('hebreo', models.CharField(blank=True, help_text='Nombre en hebreo', max_length=50)),
                ('fonetica', models.CharField(blank=True, help_text='Transcripción fonética', max_length=50)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['num'],
            },
        ),
    ]
